export const sampleSchema2 = [
  {
    "0": {
      icon: {},
      type: "LogoHeader",
      label: "Logo Header",
      imageUrl: "/logo.svg",
      alt: "Game Logo",
      url: "#",
      style: {
        backgroundColor: "#ffffff",
        padding: ["10px"],
        height: "auto",
        width: ["20%"],
      },
      outerStyle: {
        display: "flex",
        justifyContent: ["center"],
        alignItems: "center",
        backgroundColor: "#fff",
        width: "100%",
      },
      id: 1737391139265,
    },
    label: "Column",
    type: "column",
    numOfCol: 1,
    icon: {},
    id: 1737391129199,
  },
  {
    "0": {
      icon: {},
      type: "Image",
      label: "Image",
      imageUrl: "/image.png",
      alt: "Game Screenshot",
      url: "#",
      style: {
        backgroundColor: "#ffffff",
        padding: "10px",
        height: "auto",
        width: ["100%"],
        margin: "0px",
        borderRadius: "5px",
      },
      outerStyle: {
        display: "flex",
        width: "100%",
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#fff",
      },
      id: 1737391168265,
    },
    label: "Column",
    type: "column",
    numOfCol: 1,
    icon: {},
    id: 1737390120654,
  },
  {
    "0": {
      icon: {},
      type: "Text",
      label: "Text",
      textarea:
        "Experience the thrill of high-speed racing with our brand new game! Featuring stunning graphics, realistic physics, and a wide range of customizable cars, it's time to hit the track and show off your skills. Download now and start your racing journey!",
      style: {
        backgroundColor: "#fff",
        color: "#666666",
        padding: "10px",
        textAlign: "center",
        fontSize: ["16px"],
        fontWeight: "normal",
        textTransform: ["capitalize"],
      },
      id: 1737391200299,
    },
    label: "Column",
    type: "column",
    numOfCol: 1,
    icon: {},
    id: 1737390127325,
  },
  {
    "0": {
      icon: {},
      label: "Button",
      type: "Button",
      content: "Download Now",
      url: "#",
      style: {
        textAlign: "center",
        backgroundColor: ["#007bff"],
        color: "#ffffff",
        padding: "10px 20px",
        width: "auto",
        fontSize: "18px",
        borderRadius: "5px",
        fontWeight: "bold",
        objectFit: "contain",
      },
      outerStyle: {
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        width: "100%",
      },
      id: 1737391224649,
    },
    label: "Column",
    type: "column",
    numOfCol: 1,
    icon: {},
    id: 1737391222432,
  },
  {
    "0": {
      icon: {},
      type: "Image",
      label: "Image",
      imageUrl: "/image.png",
      alt: "Image",
      url: "#",
      style: {
        backgroundColor: "#ffffff",
        padding: "10px",
        height: "50%",
        width: ["57%"],
        margin: "0px",
        borderRadius: ["27px"],
      },
      outerStyle: {
        display: "flex",
        width: "100%",
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#fff",
      },
      id: 1737498314120,
    },
    "1": {
      icon: {},
      type: "Text",
      label: "Text",
      textarea:
        "Experience the thrill of high-speed racing with our brand new game! Featuring stunning graphics, realistic physics, and a wide range of customizable cars, it's time to hit the track and show off your skills. Download now and start your racing journey!",
      style: {
        backgroundColor: "#fff",
        color: "#000000",
        padding: "10px",
        textAlign: ["left"],
        fontSize: ["13px"],
        fontWeight: "normal",
        textTransform: ["capitalize"],
      },
      id: 1737498315970,
    },
    label: "2 Column",
    type: "column",
    numOfCol: 2,
    icon: {},
    id: 1737498304253,
  },
];

export const sampleSchema = [
  {
    "0": {
      icon: {},
      type: "LogoHeader",
      label: "Logo Header",
      imageUrl: "/logo.svg",
      alt: "AI Writing Tool Logo",
      url: "#",
      style: {
        backgroundColor: "#ffffff",
        padding: ["10px"],
        height: "auto",
        width: ["20%"],
      },
      outerStyle: {
        display: "flex",
        justifyContent: ["center"],
        alignItems: "center",
        backgroundColor: "#fff",
        width: "100%",
      },
      id: 1737391139265,
    },
    label: "Column",
    type: "column",
    numOfCol: 1,
    icon: {},
    id: 1737391129199,
  },
  {
    "0": {
      icon: {},
      type: "Text",
      label: "Introducing the Future of Content Creation",
      textarea:
        "🚀 Revolutionize your content creation with our cutting-edge AI writing tool! Say goodbye to tedious writing and hello to high-quality content that drives results. 📝",
      style: {
        backgroundColor: "#fff",
        color: "#000000",
        padding: "10px",
        textAlign: "center",
        fontSize: ["24px"],
        fontWeight: "bold",
        textTransform: ["capitalize"],
      },
      id: 1737391200299,
    },
    label: "Column",
    type: "column",
    numOfCol: 1,
    icon: {},
    id: 1737390127325,
  },
  {
    "0": {
      icon: {},
      type: "Image",
      label: "Image",
      imageUrl: "/image.png",
      alt: "AI Writing Tool Screenshot",
      url: "#",
      style: {
        backgroundColor: "#ffffff",
        padding: "10px",
        height: "auto",
        width: ["100%"],
        margin: "0px",
        borderRadius: "5px",
      },
      outerStyle: {
        display: "flex",
        width: "100%",
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#fff",
      },
      id: 1737391168265,
    },
    label: "Column",
    type: "column",
    numOfCol: 1,
    icon: {},
    id: 1737390120654,
  },
  {
    "0": {
      icon: {},
      type: "Text",
      label: "Unlock the Power of AI-Driven Content",
      textarea:
        "✍️ Our AI writing tool helps you create high-quality content that resonates with your audience. From blog posts to social media updates, our tool ensures that your content is engaging, informative, and optimized for performance. 📊",
      style: {
        backgroundColor: "#fff",
        color: "#666666",
        padding: "10px",
        textAlign: "center",
        fontSize: ["16px"],
        fontWeight: "normal",
        textTransform: ["capitalize"],
      },
      id: 1737498315970,
    },
    "1": {
      icon: {},
      type: "Text",
      label: "Text",
      textarea:
        "💡 With our AI writing tool, you can:\n✨ Generate high-quality content in minutes\n✨ Improve your content's performance with data-driven insights\n✨ Enhance your brand's voice and tone\n✨ Save time and increase productivity",
      style: {
        backgroundColor: "#fff",
        color: "#000000",
        padding: "10px",
        textAlign: ["left"],
        fontSize: ["13px"],
        fontWeight: "normal",
        textTransform: ["capitalize"],
      },
      id: 1737498314120,
    },
    label: "2 Column",
    type: "column",
    numOfCol: 2,
    icon: {},
    id: 1737498304253,
  },
  {
    "0": {
      icon: {},
      type: "Button",
      label: "Get Started Today",
      content: "Get Started Today",
      url: "#",
      style: {
        textAlign: "center",
        backgroundColor: ["#007bff"],
        color: "#ffffff",
        padding: "10px 20px",
        width: "auto",
        fontSize: "18px",
        borderRadius: "5px",
        fontWeight: "bold",
        objectFit: "contain",
      },
      outerStyle: {
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        width: "100%",
      },
      id: 1737391224649,
    },
    label: "Column",
    type: "column",
    numOfCol: 1,
    icon: {},
    id: 1737391222432,
  },
];
